version: '3'
services:
  nginx:
    build: nginx
    depends_on: 
    - phabricator
    ports:
    - "8080:80"
    volumes:
    - ./data/phabricator:/srv/phd/phabricator
  phabricator:
    image: marcpar/phabricator
    volumes: ./data/phabricator:/srv/phd/phabricator
  mysql:
    image: marcpar/phabricator-mysql

  